title: FMOD GGJ 2026
description: FMOD Related Information
theme: just-the-docs
logo: "/assets/Logo/FMOD Logo White - Transparent Background.png"
title_only_log0: true

url: https://ggj.fmod.com

search_enabled: false

# Color scheme supports "light" (default) and "dark"
color_scheme: dark

