title: Global Game Jam 2026
description: FMOD Related Information
theme: just-the-docs

url: https://ggj.fmod.com

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template

search_enabled: false

# Color scheme supports "light" (default) and "dark"
color_scheme: dark

